This project is meant to serve the purpose of learning and getting used to creating websites with the use of responsive design practices.
    This involves the use of media queries to accomodate different sized devices, designing CSS while keeping flexibility in mind, and also 
    heavily uses appropriate, semantic HTML.

This project is simply a clone of thenextweb.com and is a project that is part of "The Odin Project's" online curriculum. It only consists of barebones files
to simply practice HTML and CSS with no use of Javascript. 

The CSS reset that is used in this project is the Meyer Web 2.0 reset that is widely used everywhere. The reset can be easily found on the internet.

